# Generated by Django 4.1.3 on 2023-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowsubhydro_api', '0002_alter_floodseveritymodel_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodseveritymodel',
            name='creation_date',
            field=models.CharField(default='20/03/2023 15:23:17', max_length=255),
        ),
    ]
