# Generated by Django 4.1.3 on 2023-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodSeverityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.TextField()),
                ('flood_severity_lvl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
