# Generated by Django 4.1.7 on 2023-03-26 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yellowsubhydro_api', '0005_alter_floodseveritymodel_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodseveritymodel',
            name='floodAreaID',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
